spring:
   application:
      name: ${SPRING_APPLICATION_NAME:springsecsection1}
   security:
      user:
         name: ashu_tiwary
         password: Demo@123
   datasource:
      url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
      username: ${DATABASE_USERNAME:root}
      password: ${DATABASE_PASSWORD:password}
   jpa:
      show-sql: ${JPA_SHOW_SQL:true}
      properties:
         hibernate:
            format_sql: ${HIBERNATE_FORMAT_SQL:false}
   config:
      activate:
         on-profile: qa         
   

   
logging:
   pattern:
      console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
   level:
      org:
         springframework:
            security: ${SPRING_SECURITY_LOG_LEVEL:ERROR}   

           
            