spring:
   application:
      name: ${SPRING_APPLICATION_NAME:springsecsection1}
   security:
      user:
         name: ashu_tiwary
         password: Demo@123
         
   

   
logging:
   pattern:
      console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
   level:
      org:
         springframework:
            security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}   
    